"""DenseNet-201 feature extraction using the official Part 1 file_list.csv.

This role-owned script does not split, clean, or relabel the dataset. It reads
the file list generated by ``src/preprocessing/make_split.py`` and preserves
the original 20-class labels for compatibility with the shared validator. It
also saves fresh/rotten binary labels for the agreed main task.

Usage:
  python src/feature_extraction/extract_densenet201_official.py \
      --data-dir path/to/dataset --case no_aug
  python src/feature_extraction/extract_densenet201_official.py \
      --data-dir path/to/dataset --case aug
"""

from __future__ import annotations

import argparse
import json
import os
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms
from tqdm import tqdm

ROOT = Path(__file__).resolve().parents[2]
FILE_LIST = ROOT / "docs" / "file_list.csv"
SEED = 42
FEATURE_DIM = 1920
MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]


def set_seed() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(SEED)


def binary_label(label: str) -> str:
    value = label.lower().replace(" ", "").replace("_", "").replace("-", "")
    if value.startswith("fresh"):
        return "fresh"
    if value.startswith("rotten"):
        return "rotten"
    raise ValueError(f"Unknown freshness label: {label}")


def make_transform(case: str, split: str) -> transforms.Compose:
    normalise = [transforms.ToTensor(), transforms.Normalize(MEAN, STD)]
    if case == "aug" and split == "train":
        return transforms.Compose(
            [
                transforms.RandomResizedCrop(224, scale=(0.85, 1.0)),
                transforms.RandomHorizontalFlip(0.5),
                transforms.RandomRotation(10),
                transforms.ColorJitter(0.15, 0.15, 0.10, 0.03),
                *normalise,
            ]
        )
    return transforms.Compose([transforms.Resize((224, 224)), *normalise])


class OfficialDataset(Dataset):
    def __init__(self, frame: pd.DataFrame, case: str, split: str):
        self.frame = frame.reset_index(drop=True)
        self.case = case
        self.split = split
        self.transform = make_transform(case, split)

    def __len__(self) -> int:
        return len(self.frame)

    def __getitem__(self, index: int):
        row = self.frame.iloc[index]
        image = Image.open(row.filepath).convert("RGB")
        if self.case == "aug" and self.split == "train":
            with torch.random.fork_rng(devices=[]):
                torch.manual_seed(SEED + index)
                image_tensor = self.transform(image)
        else:
            image_tensor = self.transform(image)
        return image_tensor, row.label, binary_label(row.label), row.filepath


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", required=True)
    parser.add_argument("--case", choices=["no_aug", "aug"], required=True)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")
    args = parser.parse_args()

    if not os.path.isdir(args.data_dir):
        raise FileNotFoundError(args.data_dir)
    if not FILE_LIST.is_file():
        raise FileNotFoundError(f"Missing {FILE_LIST}; run make_split.py first")
    set_seed()
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    device_name = "cuda" if args.device == "auto" and torch.cuda.is_available() else args.device
    device = torch.device("cpu" if device_name == "auto" else device_name)

    frame = pd.read_csv(FILE_LIST)
    if not {"filepath", "label", "split"}.issubset(frame.columns):
        raise ValueError("file_list.csv must contain filepath, label, split")
    if not frame["filepath"].map(os.path.isfile).all():
        raise FileNotFoundError("file_list.csv contains a missing image path")

    model = models.densenet201(weights=models.DenseNet201_Weights.DEFAULT)
    model.classifier = torch.nn.Identity()
    for parameter in model.parameters():
        parameter.requires_grad = False
    model.eval().to(device)

    output = ROOT / "results" / "features" / args.case
    output.mkdir(parents=True, exist_ok=True)
    metadata = {
        "model": "DenseNet-201",
        "weights": "DenseNet201_Weights.DEFAULT",
        "case": args.case,
        "task_mode": "fresh/rotten binary classification",
        "seed": SEED,
        "device": str(device),
        "feature_dim": FEATURE_DIM,
        "input": "RGB, 224x224, ImageNet mean/std",
        "source_of_split": "docs/file_list.csv generated by Part 1 make_split.py",
        "splits": {},
    }

    for split in ["train", "val", "test"]:
        split_frame = frame[frame["split"] == split].reset_index(drop=True)
        # Evaluation preprocessing is identical in both cases. Reuse its
        # no_aug outputs only when the official no_aug run already exists.
        if args.case == "aug" and split in {"val", "test"}:
            source = ROOT / "results" / "features" / "no_aug"
            if (source / f"densenet201_{split}_features.npy").is_file():
                for suffix in ["features", "labels", "binary_labels"]:
                    np.save(
                        output / f"densenet201_{split}_{suffix}.npy",
                        np.load(source / f"densenet201_{split}_{suffix}.npy", allow_pickle=True),
                    )
                metadata["splits"][split] = {"rows": len(split_frame), "reused_from": "no_aug"}
                continue

        loader = DataLoader(
            OfficialDataset(split_frame, args.case, split),
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=device.type == "cuda",
        )
        features, source_labels, binary_labels, paths = [], [], [], []
        started = time.perf_counter()
        with torch.no_grad():
            for images, source_batch, binary_batch, path_batch in tqdm(loader, desc=f"{args.case}/{split}"):
                values = model(images.to(device, non_blocking=True)).reshape(images.shape[0], -1)
                if values.shape[1] != FEATURE_DIM:
                    raise RuntimeError(f"Expected {FEATURE_DIM}, got {tuple(values.shape)}")
                features.append(values.cpu().numpy().astype(np.float32, copy=False))
                source_labels.extend(source_batch)
                binary_labels.extend(binary_batch)
                paths.extend(path_batch)
        expected_paths = split_frame["filepath"].tolist()
        expected_source = split_frame["label"].astype(str).tolist()
        if paths != expected_paths or source_labels != expected_source:
            raise RuntimeError(f"Order mismatch in official {split} file_list")
        matrix = np.concatenate(features, axis=0)
        np.save(output / f"densenet201_{split}_features.npy", matrix)
        np.save(output / f"densenet201_{split}_labels.npy", np.asarray(source_labels, dtype=str))
        np.save(output / f"densenet201_{split}_binary_labels.npy", np.asarray(binary_labels, dtype=str))
        metadata["splits"][split] = {
            "rows": int(matrix.shape[0]),
            "feature_dim": int(matrix.shape[1]),
            "seconds": round(time.perf_counter() - started, 3),
            "fresh": int(binary_labels.count("fresh")),
            "rotten": int(binary_labels.count("rotten")),
        }

    with open(output / "metadata.json", "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2)
    print(json.dumps(metadata, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
