"""
Stage: Feature Extraction
Role: Member 3 - ResNeXt-101 feature extraction

This script reads docs/file_list.csv in the original row order,
extracts image features using a frozen ImageNet-pretrained ResNeXt-101,
and saves the feature matrix and labels to results/features/.

IMPORTANT:
- Do not shuffle rows.
- Do not create a new split.
- Use docs/file_list.csv generated by make_split.py.
"""

from pathlib import Path
import time

import numpy as np
import pandas as pd
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models


# =========================
# Settings
# =========================

FILE_LIST = Path("docs/file_list.csv")
OUTPUT_DIR = Path("results/features")

FEATURE_PATH = OUTPUT_DIR / "resnext101_features.npy"
LABEL_PATH = OUTPUT_DIR / "resnext101_labels.npy"
SPLIT_PATH = OUTPUT_DIR / "resnext101_splits.npy"

BATCH_SIZE = 32
NUM_WORKERS = 0

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)


# =========================
# Dataset
# =========================

class FileListImageDataset(Dataset):
    def __init__(self, file_list_csv, transform=None):
        self.df = pd.read_csv(file_list_csv)
        self.transform = transform

        required_cols = {"filepath", "label", "split"}
        missing = required_cols - set(self.df.columns)
        if missing:
            raise ValueError(f"Missing columns in file_list.csv: {missing}")

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        image_path = row["filepath"]
        label = row["label"]
        split = row["split"]

        image = Image.open(image_path).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        return image, label, split


# =========================
# Model
# =========================

def build_resnext101_feature_extractor(device):
    weights = models.ResNeXt101_32X8D_Weights.DEFAULT
    model = models.resnext101_32x8d(weights=weights)

    # Remove final classification layer.
    # Original model:
    # conv layers -> avgpool -> flatten -> fc
    # We keep everything before fc.
    model.fc = torch.nn.Identity()

    model.eval()
    model.to(device)

    return model

# =========================
# Main
# =========================

def main():
    start_time = time.time()

    if not FILE_LIST.exists():
        raise FileNotFoundError(
            "docs/file_list.csv not found. Please run make_split.py first."
        )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = build_resnext101_feature_extractor(device)

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    dataset = FileListImageDataset(FILE_LIST, transform=transform)

    loader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,          # IMPORTANT: row order must be preserved
        num_workers=NUM_WORKERS
    )

    all_features = []
    all_labels = []
    all_splits = []

    print(f"Extracting ResNeXt-101 features from {len(dataset)} images...")

    with torch.no_grad():
        for batch_idx, (images, labels, splits) in enumerate(loader):
            images = images.to(device)

            features = model(images)
            features = features.cpu().numpy()

            all_features.append(features)
            all_labels.extend(labels)
            all_splits.extend(splits)

            if (batch_idx + 1) % 10 == 0:
                processed = min((batch_idx + 1) * BATCH_SIZE, len(dataset))
                print(f"... processed {processed}/{len(dataset)} images")

    features_array = np.concatenate(all_features, axis=0)
    labels_array = np.array(all_labels)
    splits_array = np.array(all_splits)

    np.save(FEATURE_PATH, features_array)
    np.save(LABEL_PATH, labels_array)
    np.save(SPLIT_PATH, splits_array)

    elapsed = time.time() - start_time

    print("\n=== ResNeXt-101 feature extraction complete ===")
    print(f"Features shape: {features_array.shape}")
    print(f"Labels shape:   {labels_array.shape}")
    print(f"Splits shape:   {splits_array.shape}")
    print(f"Saved features: {FEATURE_PATH}")
    print(f"Saved labels:   {LABEL_PATH}")
    print(f"Saved splits:   {SPLIT_PATH}")
    print(f"Elapsed time:   {elapsed:.2f} seconds")


if __name__ == "__main__":
    main()